### ISSUE TITLE
The dials are not working

### ISSUE THREAD

**Issue by TrendMend** [thetazzbot/FreeExpression#10]
Title ^

They are stuck on 3, both of them...

**Comment by markawilliamson** [comment]
Yeah use the buttons. I think I documented them

**Comment by TrendMend** [comment]
Sounds good, so the dials mean nothing then? like I can use the buttons up to 10 but your documentation said to use them in conjunction with the dials because of the pot limits or something (I cant fully remember).

**Comment by markawilliamson** [comment]
Some machines have encoders some have potentiometer, and at one time the
code was working. Then I merged code from a pull request and it hasn't
worked since then. There are F1...10 buttons that do a few things. Then
press +- buttons to change values

**Comment by TrendMend** [comment]
Okay, that works for me, it would be nice to have it remember the settings, but no biggie. Just to confirm, the function keys you are speaking of are these? https://github.com/thetazzbot/FreeExpression#keypad-key-functions Thanks.
