### ISSUE TITLE
Some errors when building.

### ISSUE THREAD

**Issue by icebox3557** [thetazzbot/FreeExpression#14]
When I try to build FreeExpression.cproj in AtmelStudio 7 I get 4 errors.
The first is: Disabling relaxation: it will not work with multiple definitions
Second: recipe for target 'FreeExpression.elf' failed
Third: multiple definition of 'main'
Fourth: Id returned 1 exit status
Sorry if I'm missing something obvious, this is my first time using AtmelStudio, thanks

**Comment by markawilliamson** [comment]
I can't help much, but I just confirmed it still compiles. I pushed my
locally changed code to github, but I don't know how working it is.  It's
been a while since I ran it.

[image: image.png]

**Comment by icebox3557** [comment]
That worked, thanks.

**Comment by wildseyed** [comment]
> That worked, thanks.

Hmm. I don't think that is what fixed your problem. I'm getting the same four errors you mentioned, and I downloaded the master today. Can you recall anything else you may have done in  Atmel Studio?

**Comment by icebox3557** [comment]
IIRC it wasn't working I made this post, he uploaded it I downloaded it and hit rebuild FreeExpression and then it WORKED. (I think I may have just been hitting the wrong thing) I'll post again if I find a better answer. P. S. This is with Atmel Studio 7.0.2397

**Comment by wildseyed** [comment]
I'm equally puzzled now. I downloaded again and built, and now it works. I didn't do anything else.

**Comment by markawilliamson** [comment]
Magic!  Cheers,
Mark

PS it wasn't me.  I just uploaded whatever changes I had after confirming
it compiled.  I'd love to work on this project more but I don't really have
a need for it at the moment.  I'll help where I can.
