### ISSUE TITLE
Release Build - Errors, Debug Build - No LCD, No Comms

### ISSUE THREAD

**Issue by wildseyed** [thetazzbot/FreeExpression#15]
The debug build compiles with no problems, but the release throws over 30 errors.

Flashing the debug build results in no LCD display, and attempting to cut from inkscape does nothing.

Using Atmel Studio 7

**Comment by keen101** [comment]
i think i got mine to compile under windows but it spit out 39 errors and i have no idea where the hex file is.

still haven't gotten it to compile under linux. will try doing a distro upgrade and see if that upgrades my gcc-avr library.

**Comment by wildseyed** [comment]
I'm closing this issue. It turns out that the current release does not display text at boot, and I was expecting to see a version display as seen in this picture http://www.thetazzbot.com/wp-content/uploads/2015/02/20150218_082228.jpg, so this led me to believe that something had gone wrong (because the display was blank).
