### ISSUE TITLE
Getting cricut to print

### ISSUE THREAD

**Issue by Danielb978551** [thetazzbot/FreeExpression#23]
I was able to flash the firmware, and the cricut behaves correctly. But I can't get the plot feature to work in inkscape. All of my settings seem correct. Is there a driver I need to install?

**Comment by ellisgl** [comment]
@Danielb978551 what was the fix?

**Comment by Danielb978551** [comment]
It turned out to be the pc that was the issue. I hooked up the cricut to
another pc and it worked perfect. Thanks again for this dope ass firmware!
