### ISSUE TITLE
Question about using the original OLED display

### ISSUE THREAD

**Issue by nathanaelhuffman** [thetazzbot/FreeExpression#8]
I see the current version of the master branch is using a replaced LCD, but your blog posts from a while back indicate that you got the original OLED interface working.  I've just gotten the project all set up, ported to MPLAB-X (turned off the prototype warnings so it builds) and am flashing my expression via ISP interface.

Is there an easy way to re-enable the original OLED interface in the master branch, if not I guess I'm going to go about trying to back those changes out?  Where there issues with the OLED that made the move to a serial LCD make sense?  I'd prefer not to replace the screen on mine since I don't plan to do much development, the original display sharing jtag doesn't really bother me.

**Comment by markawilliamson** [comment]
I'll take a look and let you know!

Thanks

**Comment by nathanaelhuffman** [comment]
I actually did figure it out last weekend.  I reverted some of the stuff that was merged in and got it working with the original LCD.  I also ported the design to MPLABX.  One thing that might be helpful is a list of the expected fuse settings, this may have been lost in the AVR Studio to MPLABX port but I kind of had to figure the clock settings by trial and error after noticing everything ran really slow with the default clock settings and the COM port didn't work.  After getting the clock running everything behaves as expected.  Thanks for your work on this, it's nice to be able to use the hardware like I want to!

**Comment by markawilliamson** [comment]
It's nice to see others using it. Be sure to fork my branch and commit your
changes with notes, others might find it useful

**Comment by nathanaelhuffman** [comment]
I just did.  Thanks again

**Comment by markawilliamson** [comment]
The master has been updated with corrections and defines to swtich between LCD and oled display. I look forward to seeing your updates. I am trying to improve much of the code as I re-enter the avr development hobby.
