### ISSUE TITLE
Issues with size/scale....

### ISSUE THREAD

**Issue by TrendMend** [thetazzbot/FreeExpression#9]
So I seem to be having a odd issue. I am using inkcut (the revival), and even though the settings are all correct, for some reason the cricut is not liking the scaling at all. This is giving me a 5 inch emblem in the size of the entire mat (beyond the borders). Is there a reason this is happening?

**Comment by TrendMend** [comment]
Soo, I just tried it out with inkscape with the same issue... So it seems to be on the cricut end of things. Any idea?

**Comment by TrendMend** [comment]
It was the dpi :P make sure to set it to 400 lol

**Comment by markawilliamson** [comment]
I was going to reply about that but I wanted to check first ;)  I've run
into this myself and was thinking it was 400...

**Comment by markawilliamson** [comment]
If you're using Inkscape, Extensions, Export, Plot, then Resolution X and Y
should be 400
